# Generated by Django 4.1.13 on 2024-04-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCar', '0006_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
